name: Deploy Laravel ke VPS

on:
  push:
    branches:
      - main  # Ganti jika kamu pakai branch lain

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy ke VPS via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        script: |
          cd /var/www/html/Vitalife
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
